### ISSUE TITLE
hide and show HUD 

### ISSUE THREAD

**Issue by stephanschulz** [freshfork/p5.EasyCam#16]
I am working off the [CameraStates](https://freshfork.github.io/p5.EasyCam/examples/CameraStates/) example.
What do i have to do to hide or show the text and screenshot HUD overlays?
Unfortunately i am not super experienced with css and html to know how to set the hide/show from JS.

Thanks a bunch.

**Comment by jwdunn1** [comment]
Depending on the element ID for the HUD overlay, it can be toggled on/off using one of the following:
document.getElementById('easycamhud').style.display ='block';  // to display
document.getElementById('easycamhud').style.display ='none';  // to hide

**Comment by stephanschulz** [comment]
Thanks so much for adding to the example. It is very helpful to me.

Since i am using your example in combination with [dat.GUI](https://github.com/dataarts/dat.gui/blob/master/API.md), i added this code to toggle the HUD drawing via key 'h', which dat.GUI listens to.

```
  if(key == 'h'){
    // console.log("datGui.hide ",datGui.domElement.style.display);
    if(datGui.domElement.style.display === ''){
      document.getElementById('easycamhud').style.display ='block'; // hide HUD
      document.getElementById('statehud').style.display ='block';
    }
    else {
      document.getElementById('easycamhud').style.display ='none'; // display HUD
      document.getElementById('statehud').style.display ='none'; 
    }
  }
```
