### ISSUE TITLE
2d text renders badly

### ISSUE THREAD

**Issue by stephanschulz** [freshfork/p5.EasyCam#17]
My canvas uses WEBGL and i am trying to draw regular debug text on top in 2D.

I am following this WEBGL method  https://p5js.org/reference/#/p5/text

```
function preload() {
  inconsolata = loadFont(
    "https://cdnjs.cloudflare.com/ajax/libs/bwip-js/2.0.6/Inconsolata.otf"
  );
}

function setup() {
  pixelDensity(1); //lower is faster

  var canvas = createCanvas(windowWidth, windowHeight, WEBGL);
  
  textFont(inconsolata);
  textSize(20);
  textAlign(CENTER, CENTER);
```

Drawing text inside `displayHUD()` makes it look very glitchy. 
drawing text inside `draw()` is glitchy too but in 3D space.

<img width="783" alt="Screen Shot 2022-02-26 at 3 52 25 PM" src="https://user-images.githubusercontent.com/1054816/155858844-98cc102b-60ec-492c-beb1-5a59424c6dc5.png">
<img width="653" alt="Screen Shot 2022-02-26 at 3 53 15 PM" src="https://user-images.githubusercontent.com/1054816/155858846-5864ab6f-2f64-42a0-bd7b-82901df064ab.png">

**Comment by stephanschulz** [comment]
Oh strange. 
I am on macOS and in chrome it looks bad and in Safari and Firefox it looks fine.

**Comment by jwdunn1** [comment]
I've been trying to reproduce this issue here: https://editor.p5js.org/jwdunn1/sketches/CXWVcu8mR
Unsuccessfully thus far.
Are you running the latest Chrome (v 98.0.4758.102)?

**Comment by stephanschulz** [comment]
macOS chrome Version 98.0.4758.109 (Official Build) (x86_64)
<img width="1658" alt="Screen Shot 2022-03-01 at 7 59 40 PM" src="https://user-images.githubusercontent.com/1054816/156274486-83044d76-39b9-4eb5-be70-c958d9536490.png">

**Comment by jwdunn1** [comment]
Nice! And your Mac OS version?

**Comment by stephanschulz** [comment]
macOS 10.15.7

**Comment by stephanschulz** [comment]
macOS 10.15.7

**Comment by jwdunn1** [comment]
Can you upgrade your OS? Or is your hardware preventing this? I do see some odd Chrome issues reported last year related to 10.15.7 [here](https://forums.macrumors.com/threads/strange-chrome-browser-graphical-glitches.2229803/page-3). I'm not seeing this font glitching behavior on an iMac Pro running macOS 11.6 (Big Sur) with the latest Chrome version.

**Comment by stephanschulz** [comment]
sorry can't update my dev computer. needs to stay as is.
but I confirmed that on iPad + safari and on a macOS 11.2 computer + chrome the text looks fine. 
so, it's the 10.15.7 . good to know. 

Thanks again for all your help.

**Comment by jwdunn1** [comment]
One other thing to try. If you are using a lighting model in your draw loop, be sure to turn that off in the HUD, otherwise objects are shaded using that lighting model. This would affect how fonts are shaded too. For example, if the standard lighting model `lights()` is called in the draw loop, then call `noLights()` in the HUD code.
I've updated [the sketch](https://editor.p5js.org/jwdunn1/sketches/CXWVcu8mR) so you can try it there first.

**Comment by stephanschulz** [comment]
I just tried your example and also tried adding the `lights()` suggestion but it did not change anything :(
Overall it's not a big problem since i can just tell people to use a specific browser.
