### ISSUE TITLE
Problem/fix for instance mode with p5 1.4.2

### ISSUE THREAD

**Issue by v-k-** [freshfork/p5.EasyCam#20]
Hello. 

When using the library in instance mode, it breaks with` p5 1.4.2`. I don't have the error here, but it complains that does not know  the function `camera`.

The problem is at line 628 (no minified), somehow the reference to the p5 object (I believe should be `_curCamera`) is lost and p5's function `camera()` is not recognized. I fixed it in a local copy, using the hidden p5's variable `_pInst` instead of `_curCamera`, everything went fine that way. Although this fixes the issue, I believe it's probably not the right way to do it, hence not a pull request, just this issue message. 
Thanks for the excellent work.
cheers
Vicente

ps: I'm not with my computer right now, so I can't provide a MRE, but can do it later if you guys want. Sorry about that.

**Comment by jwdunn1** [comment]
Thank you for using p5.EasyCam! [Here is a sketch](https://editor.p5js.org/jwdunn1/sketches/_wELDF2eh) that demonstrates proper **instance mode** operation of EasyCam with the latest release of p5js (v1.4.2). Please check that you are running the latest version of EasyCam. The index.html of the sketch includes the latest version by way of referring directly to the repo, or it can be included from the CDN link given in the readme.

**Comment by v-k-** [comment]
Man... thanks for your time. Actually I was using a previous release, not of EasyCam, but of p5ja!!! Everything is fine with the correct version. Sorry, and thanks again.
