### ISSUE TITLE
Distance from point to camera

### ISSUE THREAD

**Issue by jersonlatorre** [freshfork/p5.EasyCam#21]
Is there any way to calculate the distance from a point to the camera plain even if the camera is rotating?

**Comment by jwdunn1** [comment]
The camera has a `getPosition()` method which returns the camera's position in the 3D space. Use the p5 method `dist()` to determine the distance between any points in space. I've updated [this sketch](https://openprocessing.org/sketch/1503910) to demonstrate. It finds the distance between the camera and the two end points of a line segment that runs through a cube. Then, in the HUD, depending on the mouse position, displays the distance.

**Comment by intuylab** [comment]
Thank you very much @jwdunn1 for your answer! That helps me a lot.

**Comment by jersonlatorre** [comment]
Thank you very much @jwdunn1 for your answer! That helps me a lot.
