### ISSUE TITLE
HUD (HeadUp Display) rotates with EasyCam in New p5 1.6 Version.

### ISSUE THREAD

**Issue by marine1079** [freshfork/p5.EasyCam#24]
HUD (HeadUp Display) rotates with EasyCam in New p5 1.6 Version.

Reproduce step:
1. Clone this p5.EasyCam project.
2. Replace examples/HeadUpDisplay/index.html's p5.min.js version to 1.6.0 (Works fine from 1.2.0 to 1.5.0)

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14011993/221425794-c2d732fd-9640-47dd-bc8f-9134c67c5ab8.png">

**Comment by jwdunn1** [comment]
Thank you for the 'heads up' on this issue! I will investigate.

**Comment by jwdunn1** [comment]
New release of p5.EasyCam v1.2.2 fixes this issue. HUD [sketches](https://freshfork.github.io/p5.EasyCam/examples/HeadUpDisplay) now working with p5.js v1.6.0.

**Comment by marine1079** [comment]
It works fine. Thank you @jwdunn1
