### ISSUE TITLE
Documentation: How to assign pan to left mouse drag etc?

### ISSUE THREAD

**Issue by berni421** [freshfork/p5.EasyCam#29]
Could the documentation please show how to use the handlers .. e.g from Peasycam

PeasyDragHandler handler = cam.getPanDragHandler();
cam.setLeftDragHandler(handler);

Thanks

**Comment by jwdunn1** [comment]
Although there is no API for this, here is a sketch that demonstrates [how to swap the handlers](https://openprocessing.org/sketch/1938173). I'll add a link to the readme for the next release.

**Comment by berni421** [comment]
Perfect thanks
