### ISSUE TITLE
example showing camera from a specific coordinate 

### ISSUE THREAD

**Issue by jtoy** [freshfork/p5.EasyCam#3]
how would you set the camera as if we were looking from the first person point of view? I am not able to get that to work looking through the examples and docs.  is this something easycam can do?

**Comment by jwdunn1** [comment]
First-person PoV is precisely why I created p5.RoverCam.
See: https://github.com/freshfork/p5.RoverCam

**Comment by jtoy** [comment]
thanks, I found that afterwards and already tested it out, thanks! It looks good, I'll send feedback in the other repo.

**Comment by jwdunn1** [comment]
I added a link for RoverCam to the readme. Closing this issue.

**Comment by jtoy** [comment]
great, thanks!
