### ISSUE TITLE
Can't use smooth() after creating cam

### ISSUE THREAD

**Issue by jonek** [freshfork/p5.EasyCam#6]
When I call `smooth()` [1] after I created the camera, mouse interactions do not work anymore.

When I call `smooth()` before creating the camera, everything is working as expected.

Here is an [example](https://editor.p5js.org/jonek/sketches/nQP8YtxOY) in the p5 editor.

[1] https://p5js.org/reference/#/p5/smooth

**Comment by jwdunn1** [comment]
Update the example sketch to use the latest version of p5. (i.e. update index.html to point at: https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.js) Then `smooth()` works before or after creating the camera.

**Comment by jonek** [comment]
Thanks! This resolved the issue.
